### ISSUE TITLE
Test failed. Disk space issue

### ISSUE THREAD

**Issue by ericcirone** [gmetais/YellowLabTools#407] opened 2024-03-12 14:54 UTC
<img width="738" alt="image" src="https://github.com/YellowLabTools/YellowLabTools/assets/10419347/54780349-b135-413a-b1c1-26d1f4dc837f">

>Phantomas failed: ENOSPC: no space left on device, mkdtemp '/tmp/puppeteer_dev_chrome_profile-7T8fmm'

**Comment by guillermodlpa** [comment] 2024-03-12 15:03
It could have been caused by a usage spike. Yellow Lab Tools was shared today in the Smashing Magazine newsletter 👀

**Comment by ericcirone** [comment] 2024-03-12 15:39
Yup, thats how i got there.

**Comment by gmetais** [comment] 2024-03-13 21:35
Thanks for reporting the issue.
It is a known bug that auto-fixes itself after a minute.
I will work on it, but I'm closing this ticket as a duplicate of #402.

**Closed as completed by gmetais** 2024-03-13 21:35 UTC
