### ISSUE TITLE
Error 1001: JavaScript profiling failed

### ISSUE THREAD

**Issue by macnjil** [gmetais/YellowLabTools#63] opened 2015-04-01 15:39 UTC
Hi,

I have this error when i try to test www.ratp.fr

Thanks

**Comment by gmetais** [comment] 2015-04-07 09:23
Hi @macnjil,

Sorry for the late response, I took a few days off.
Your problem is the same as the one described here: https://github.com/macbre/phantomas/issues/482

For the moment I have no idea why it fails. Could you tell me what JS framework or JS library you're using? It could be a clue.

**Comment by gmetais** [comment] 2015-05-26 08:52
Hi @macnjil,

I managed to understand the problem, it comes from Prototype 1.6. A full explanation here: https://github.com/macbre/phantomas/issues/482#issuecomment-105445659

**Comment by gmetais** [comment] 2015-06-28 07:47
Hi @macnjil, the problem is fixed on www.ratp.fr !

**Closed by gmetais** 2015-06-28 07:47 UTC
Labels: bug, external dependency

**Comment by macnjil** [comment] 2015-06-29 14:34
Thanks
