### ISSUE TITLE
Stylesheet analyzed twice when using loadCSS

### ISSUE THREAD

**Issue by luboskmetko** [gmetais/YellowLabTools#156] opened 2016-05-16 08:16 UTC
First of all, great tool! I've learned about it from your comment on our blog.

This is not a big deal, but was checking the results and it seems the tool is analyzing the same stylesheet twice when it's loaded via https://github.com/filamentgroup/loadCSS (first via JS and then in noscript tag).

Here are some related results:
- http://yellowlab.tools/result/eengdos4zy/rule/cssRules
- http://yellowlab.tools/result/eengdos4zy/rule/multipleRequests

**Comment by gmetais** [comment] 2016-05-18 14:20
Hi @luboskmetko,

Thank you for reporting this. Phantomas cannot recognise the usage of a file, it only detects the mime type of the response. The problem with LoadCSS is not the noscript tag, which is ignored by Phantomas.

The problem is that LoadCSS loads the file once but doesn't use it as a stylesheet, just to get the file in cache. Than it loads the file a second time as a CSS.

I have no idea how to fix this, maybe @macbre, the author of Phantomas has one. I ain't got much time, do you mind opening a issue on the [Phantomas](https://github.com/macbre/phantomas/) project please?

**Comment by luboskmetko** [comment] 2016-05-19 07:17
No problem, I've opened the issue. Not sure if I described it properly, but hopefully it will be clearer from this issue.

**Comment by gmetais** [comment] 2017-05-28 08:11
Hi @luboskmetko,

I can't reproduce the bug: http://yellowlab.tools/result/eq9u0futhy

Could you please confirm LoadCSS is still used on the page?

**Comment by luboskmetko** [comment] 2017-05-31 06:40
Hi @gmetais yes, LoadCSS is still used there. The only difference is that now we add hash to file name, eg. `main.min-3fd6d57d0b.css`.

**Comment by gmetais** [comment] 2017-05-31 16:35
The PhantomJS engine has been updated in the meanwhile and I guess it has fixed the issue.

Let's close it!

**Closed by gmetais** 2017-05-31 16:35 UTC
Labels: bug, external dependency
