### ISSUE TITLE
Error 255: Phantoms error on www.soundradix.com

### ISSUE THREAD

**Issue by danra** [gmetais/YellowLabTools#115] opened 2015-10-19 20:14 UTC
Just launched a new site, would love to use your tool.
Getting Error 255: Phantoms error.

**Comment by gmetais** [comment] 2015-10-20 06:10
Hi @danra,

Thank you for reporting the issue. I'll try to identify the problem when I get a little more time.
However it's working on my computer and I can give you two quick wins for your website:

1. Add gzip compression to HTML, CSS, JS and SVG files, it will save 669KB
2. Optimize this image to save 500KB: https://d1lurqwird8tyx.cloudfront.net/static/carousel/img/radical-bundle/bg.jpg

See you later!

**Comment by danra** [comment] 2015-10-21 15:35
The tool seems to work intermittently on my site.
Done 2 and some more. 1 seems to be a real task with hosting on s3. 

Thanks!
Dan

**Comment by gmetais** [comment] 2015-10-21 16:21
Have a look here: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html#CompressedS3

**Comment by danra** [comment] 2015-10-21 16:26
I have. As I said, not a little effort, and a headache to maintain.

**Comment by gmetais** [comment] 2015-10-29 10:57
Hi @danra,

For a mysterious reason, it's working today: http://yellowlab.tools/result/e8lshowmw1

I'm closing since I can't reproduce and find the reason of the previous failures.

**Closed by gmetais** 2015-10-29 10:57 UTC
