### ISSUE TITLE
Perform tests with mobile user agent?

### ISSUE THREAD

**Issue by RiZKiT** [gmetais/YellowLabTools#66] opened 2015-04-17 09:44 UTC
Is there a way/parameter to perform the tests with a mobile user agent? Our site checks for mobile user agent to redirect the user to mobile or desktop version.

Phantomas seems to support this, see: https://github.com/macbre/phantomas/issues/213 or https://github.com/macbre/phantomas#parameters

**Comment by gmetais** [comment] 2015-04-17 10:06
Hi RiZKiT!

It's not possible for the moment, but it's planned for v1.4 (issue #14). The problem is I'm a bit late on this release because I don't have enough time.

If you've got time, maybe you (or someone in your company) could help adding this feature? I'd be there to assist and you'd have your name in the contributors list.

**Comment by RiZKiT** [comment] 2015-04-17 13:41
Thanks for the quick answer. I took a look at the project but got lost and was unable to find the parts which have to be changed/added. ;-)

We solved the problem for us by adding a query parameter to force the variant we want to test.

**Comment by gmetais** [comment] 2015-04-27 17:38
Fixed in v1.4.0.

**Closed by gmetais** 2015-04-27 17:38 UTC
Labels: question

**Comment by RiZKiT** [comment] 2015-05-07 06:34
Thank you!
