### ISSUE TITLE
body.scrollHeight Error cause testing page fail to complete loading

### ISSUE THREAD

**Issue by lizicuenca** [gmetais/YellowLabTools#191] opened 2016-08-30 14:25 UTC
When I evaluate www.amazon.com on my build, the tool shows the total page weight is only 19.8KB with 2 requests. In the JS Timeline, I found "TypeError: null is not an object (evaluating 'body.scrollHeight')" as the third row in the table. And nothing else is loaded after the JS error.  

When I run phantomas directly, I got success result.  There are 46 requests and 2MB of bodySize. 
`DEBUG=* phantomas "http://www.amazon.com" --verbose`

So search around and found a thread mention about getting phamtonJS viewport. Here is what get when run phantomjs from the server. 
`ubuntu@ip:~$ phantomjs pageHeight.js
{
    "document.body.scrollHeight": 9605,
    "document.body.offsetHeight": 9605,
    "document.documentElement.clientHeight": 300,
    "document.documentElement.scrollHeight": 9605
}
`
Sample code is copy from this thread: http://stackoverflow.com/questions/31245553/how-to-get-the-height-of-a-full-html-page-in-phantomjs-javascript

However, when I test amazon.com in http://yellowlab.tools/, this is no issue. Unfortunary, my site is running same error for every page. Can't use this tool now :(

nodejs: v6.4.0
npm: 3.10.3
phantomjs: 2.1.1
YellowLabTools: download from git 3 days ago.

**Comment by clementbuchart** [comment] 2016-09-08 02:35
Hello, 
Same issue can be reproduced with https://www.auchan.fr and nodejs 4.5.0.
Works fine via http://yellowlab.tools/.
TypeError: null is not an object (evaluating 'body.scrollHeight') with private instances.

https://www.google.fr (or any very lightweight page) can be tested fine both with private and public YellowLabTools instances.

**Comment by gmetais** [comment] 2016-09-08 07:20
I'm not able to reproduce the bug (neither amazon nor auchan) on my local instance.

Could you please copy here the error stack trace? You can find it on the JS Timeline page, just click on red warning icon on the right.

**Comment by lizicuenca** [comment] 2016-09-08 18:52
Here is the screenshot from the timeline: 
![image](https://cloud.githubusercontent.com/assets/17348533/18362482/d6fdb904-75d3-11e6-86df-7ccd4438668e.png)

**Comment by clementbuchart** [comment] 2016-09-09 09:04
If you're familiar with docker, this Dockfile should allow you to reproduce the bug : 

`FROM    node:4.5

RUN     npm install -g npm@latest \
        && npm install -g node-gyp \
        && npm install -g grunt-cli

ENV     COMMIT=c82c1c192f9fb49f18b4c8206b6bfb95fd8f1d2b
RUN     mkdir /opt/ylt && cd /opt/ylt \
        && git clone https://github.com/gmetais/YellowLabTools.git . \
        && git checkout ${COMMIT} \
        && npm install \
        && grunt build

WORKDIR /opt/ylt

EXPOSE  8383

ENV     NODE_ENV=production
CMD     ["node", "bin/server.js"]
`

I hosted a temp instance on AWS, it might still be available when you read this : http://52.59.233.207/result/eia3zqt9lg

I have the same stack trace as lizicuenca in the timeline

**Comment by gmetais** [comment] 2016-09-12 08:15
This stack trace is very strange... Thank you, both of you.

This Dockerfile should really help debugging. Sadly, I have a poor internet connection where I am in Indonesia. I'm stuck at Step1 `FROM node:4.5`. It just requires a few hundreds of KB to download but I've been trying dozens of times in the last 2 days and I only get timeouts or never-ending downloads... I hope I can find a better connection soon.

**Comment by gmetais** [comment] 2016-09-16 14:54
Here is another test that gets the same error, and this is on the public instance: http://yellowlab.tools/result/eii3ezjbc3/rule/jsErrors

**Comment by gmetais** [comment] 2016-09-20 15:03
I managed to reproduce the bug. This is due to the "flatten" `node_modules` directory that was introduced in npm 3. It looks like I never tried YLT with npm 3 before!

I'm opening an issue in https://github.com/macbre/phantomas about this and I'll keep you informed.

**Comment by gmetais** [comment] 2016-09-20 15:18
https://github.com/macbre/phantomas/issues/664

**Comment by macbre** [comment] 2016-09-21 20:49
@gmetais - fixed by https://github.com/macbre/phantomas/issues/665 (will be a part of v1.17)

**Comment by gmetais** [comment] 2016-09-22 01:47
@macbre That was super fast! Thanks a lot.

**Comment by gmetais** [comment] 2016-12-20 06:49
Fixed by #210.

**Closed by gmetais** 2016-12-20 06:49 UTC
Labels: bug
