### ISSUE TITLE
Generally only get 255 errors  now. 

### ISSUE THREAD

**Issue by marston-gould-apfm** [gmetais/YellowLabTools#226] opened 2017-03-25 00:21 UTC
This cannot be related to a heavy DOM.
We have re-written portions of our site from the ground up and our DOM is very light.
Webpage URL: http://www.aplaceformom.com/assisted-living/california/san-jose
Tested device: desktop
Makes a redirection: no

Page is 782kb (in total). It only makes 28 page requests
GTMetrix has fully loaded at 1.1 - 2.3s
TTFB is 139ms
DOM is loaded in 270-700ms

**Comment by rockeynebhwani** [comment] 2017-04-26 14:55
Is this duplicate of https://github.com/gmetais/YellowLabTools/issues/168

**Comment by gmetais** [comment] 2017-05-05 21:14
Hi @rockeynebhwani,
Yes, this is a duplicate of #168.

The issue is not related to heavy DOM, but to heavy DOM **access**, from JavaScript.

**Comment by gmetais** [comment] 2017-05-05 21:15
Could you please close this issue and report your failing URL in #168?

**Closed** 2018-01-17 03:12 UTC
