### ISSUE TITLE
Error 255: Phantomas error

### ISSUE THREAD

**Issue by chinmayv29** [gmetais/YellowLabTools#232] opened 2017-05-16 09:18 UTC
Hi, i am trying to run test using api but getting the error:  **Error 255: Phantomas error**

Following is the result url: http://yellowlab.tools/api/runs/epwne48ro5 

Plz let me know why the error is arising.

Thanks,
Chinmay

**Comment by gmetais** [comment] 2017-05-16 22:10
Hi @chinmayv29,

This is a known issue (#168) and the reason is not explained.
Would you mind adding your bug case there and closing this one?

Gaël

**Comment by sofilibi** [comment] 2017-06-16 15:03
Hi I have the following error msg: http://yellowlab.tools/queue/eqv3kz625k
![2017-06-16_10-02-54](https://user-images.githubusercontent.com/4973956/27232260-05688916-527b-11e7-931a-93881b784ac0.png) . Please let me know about this error, thanks

**Comment by gmetais** [comment] 2017-06-16 15:19
Hi @sofilibi,

The 254 (which is different from 255) error is generally caused by multiple redirects or JavaScript redirects. This is the case on your page, the first time user (with no cookies) is redirected as followed:

http://www.medicaresupplement.com/
https://www.medicaresupplement.com/
https://www.medicaresupplement.com/b/?utm_expid=.w9M8rCRsQOevJ5Q1dcrgEw.1&utm_referrer=
https://www.medicaresupplement.com/b/?utm_expid=.w9M8rCRsQOevJ5Q1dcrgEw.1&utm_referrer

Try to test the page with the appropriate final url or maybe the right cookie.

**Closed by gmetais** 2017-06-16 15:19 UTC

**Comment by sofilibi** [comment] 2017-06-16 15:33
Thanks very much @gmetais
