### ISSUE TITLE
Error 255 when too many DOM access on the page

### ISSUE THREAD

**Issue by youradds** [gmetais/YellowLabTools#137] opened 2016-01-09 07:28 UTC
Hi,

I've been using your online tool for a little while now. Awesome job :) However, today I started getting this error:

Test failed

Error 255: Phantomas error

Is this a temporary issue, or something wrong on our end? The page I'm getting it on, is: http://www.chambresdhotes.org/Chambres_D_Hotes/Aude_Chambres_D_Hotes/Esperaza_Chambres_D_Hotes_-_Gites_Esperaza/ 

Cheers

Andy

**Comment by gmetais** [comment] 2016-01-09 11:28
Hi Andy,

Though I didn't do anything it's not failing anymore today.

Your website is not the only one experiencing 255 errors. The problem generally comes from PhantomJS that crashes unexpectedly. Sorry I got no clue. Could it be an ad that was here yesterday and that changed today?

**Comment by youradds** [comment] 2016-01-09 11:33
Thanks for the reply. Yeah, its weird. Here is a test from yesterday (on
the same page);

http://yellowlab.tools/result/easc97mn24 86 score - 3676 DOM objects

Same page, but with just a little JS tweak (

http://yellowlab.tools/result/eat3phmcl7 - 34 score - 9410 DOM objects!

Literally the only thing that was changed, was:

$('div[id^="popup_Price_"').each( function() {

fixed to:

$('div[id^="popup_Price_]"').each( function() {

(notice the closing ], which was missing on the old one)

Really baffling :/

Cheers

Andy Newby
*Email:*    andy@ultranerds.co.uk
*WWW:    *http://www.ultranerds.co.uk
*Mobile: * 07769 201 576

**Comment by youradds** [comment] 2016-01-09 11:37
BTW - the "ads" are only standard ones that we serve up on that page (no
google ads, etc)

I'm baffled as to the DOM count. There is no way we have that many. Using
the DOM Monster bookmarklett, I get:

[image: Inline image 1]

So I'm confused as to how its thinking we have 3 times as many :(

Cheers

Andy Newby

**Comment by gmetais** [comment] 2016-01-09 11:45
9410 is not the DOM elements count, it is the number of DOM accesses.

It looks like the first test failed to interpret JS (see the JavaScript error). The second test had no error, and all the JS executed correctly (have a look at the difference between the screenshots).

I would like to reproduce the bug but it's not there anymore :/

**Comment by youradds** [comment] 2016-01-09 12:00
Hi,

Ah yes, my mistake :) Ok, maybe I'll run some tests on our dev version, and see if I can work out why its doing so many requests now.  I always seem to get this error, but I think its just PhantomJS being weird - as we don't get that in any other browsers:

TypeError: (function) is not a constructor (evaluating 'a.isImmediatePropagationStopped()')

I still get the 255 errors a few times (almost seems like a timeout issue, as it takes ago). 

Very odd (not had a single problem like this before with your service, on this page, or any others) 

Thanks

Andy

**Comment by youradds** [comment] 2016-01-09 12:13
BTW: It does seem to be working better for me now (still getting really high DOM access counts, so debugging why thats gone up so much - but I have not have a 255 error in a while now)

Thanks!

**Comment by gmetais** [comment] 2016-01-09 12:16
Your datepicker seems to do A LOT of DOM accesses.

**Comment by youradds** [comment] 2016-01-09 12:21
Hi,

Yeah - I'm trying to see if there is a better way we can do that :) The
problem is, we need one datepicker for each of the listings. I have
feeling, that we init a datepicker for EACH of them (as well as on the ajax
loaded content). I wonder if I can maybe bind a single one to ALL of them
(without having to init it every time we add a new listing into the page)

Cheers



Andy Newby
*Email:*    andy@ultranerds.co.uk
*WWW:    *http://www.ultranerds.co.uk
*Mobile: * 07769 201 576

**Comment by youradds** [comment] 2016-01-09 12:27
Hi,

Ok yeah, so you are totally right on the datepicker stuff. We have the following code (1 of them for "from" and one for "to" dates, for most listings):

    var checkin = $('.dateFrom').datepicker({
        format: 'dd-mm-yyyy',
        multidate: false,
        startDate: nowTemp,
        language: the_lang
    })
    .on('changeDate', function(ev) {

		var link_id = $(this).attr('rel');

        var newDate = new Date(ev.date)
		newDate = addDays(newDate,1);

        $('#dateFrom'+link_id).datepicker('update',ev.date);
        $('#dateFrom'+link_id).datepicker('hide');
        $('#dateTo'+link_id).datepicker('update',newDate).datepicker('setStartDate',newDate).datepicker('show');

		writeCookie('searchDateFrom',$('#dateFrom'+link_id).val(),1);
		writeCookie('searchDateTo',  $('#dateTo'+link_id).val(),1);
		writeCookie('searchNumAdults',$('#adults'+link_id).val(),1);
		writeCookie('searchNumChildren',$('#children'+link_id).val(),1);

		$('.dateFrom').val( $('#dateFrom'+link_id).val() );
		$('.dateTo').val( $('#dateTo'+link_id).val() );
		$('select[id^=adults]').val( $('#adults'+link_id).val() );
		$('select[id^=children]').val( $('#children'+link_id).val() );

    }).on("show", function() {
        $(this).blur();
    }).on("hide", function() {
    });

    var checkout = $('.dateTo').datepicker({
        format: 'dd-mm-yyyy',
        multidate: false,
        startDate: nowTemp,
        language: the_lang,
        onRender: function(date) {
	    	return date.valueOf() <= checkin.date.valueOf() ? 'disabled' : '';
	    }
    }).on('changeDate', function(ev) {

    	var link_id = $(this).attr('rel');
    	$('#dateTo'+link_id).datepicker('hide');
        if (!$('#dateFrom'+link_id).val().length) {

            var newDate = new Date(ev.date)
            newDate = removeDays(newDate,1);

            $('#dateFrom'+link_id).datepicker('update',newDate);
            $('#dateFrom'+link_id).datepicker('hide');

        }

		writeCookie('searchDateFrom',$('#dateFrom'+link_id).val(),1);
		writeCookie('searchDateTo',  $('#dateTo'+link_id).val(),1);
		writeCookie('searchNumAdults',$('#adults'+link_id).val(),1);
		writeCookie('searchNumChildren',$('#children'+link_id).val(),1);

		$('.dateFrom').val( $('#dateFrom'+link_id).val() );
		$('.dateTo').val( $('#dateTo'+link_id).val() );

		$('select[id^=adults]').val( $('#adults'+link_id).val() );
		$('select[id^=children]').val( $('#children'+link_id).val() );


    }).on("show", function() {
        $(this).blur();
    }).on("hide", function() {
    });

I think what I may do, is re-work it so that we only init the datepicker when someone click in the input - that way, the initial load will be much less.

Thanks :)

Andy

**Comment by youradds** [comment] 2016-01-09 12:46
Sweet - so I got it down to about 1550 access now :) Instead of doing all the datepickers at once - it now only init's them when they are focused. Has saved a ton of DOM work!

	$(document).on("click",'.dateFrom,.dateTo',function() {

		var link_id     = $(this).attr('id').match(/\d+/)[0];

		var $from = $('#dateFrom');
		var $to   = $('#dateTo');

		if ($from.data('been-done') == undefined || $from.data('been-done') == null) {
			// not been init'd yet, so lets do it...

			$from.data('been-done',1)
			$to.data('been-done',1);

		    var checkin = $('#dateFrom'+link_id).datepicker({
		        format: 'dd-mm-yyyy',
		        multidate: false,
		        startDate: nowTemp,
		        language: the_language
		    })
		    .on('changeDate', function(ev) {

		        var newDate = new Date(ev.date)
				newDate = addDays(newDate,1);

		        $('#dateFrom'+link_id).datepicker('update',ev.date);
		        $('#dateFrom'+link_id).datepicker('hide');
		        $('#dateTo'+link_id).datepicker('update',newDate).datepicker('setStartDate',newDate).datepicker('show');

				writeCookie('searchDateFrom',$('#dateFrom'+link_id).val(),1);
				writeCookie('searchDateTo',  $('#dateTo'+link_id).val(),1);
				writeCookie('searchNumAdults',$('#adults'+link_id).val(),1);
				writeCookie('searchNumChildren',$('#children'+link_id).val(),1);

				$('.dateFrom').val( $('#dateFrom'+link_id).val() );
				$('.dateTo').val( $('#dateTo'+link_id).val() );
				$('select[id^=adults]').val( $('#adults'+link_id).val() );
				$('select[id^=children]').val( $('#children'+link_id).val() );

		    }).on("show", function() {
		        $(this).blur();
		    });

		    var checkout = $('#dateTo'+link_id).datepicker({
		        format: 'dd-mm-yyyy',
		        multidate: false,
		        startDate: nowTemp,
		        language: the_language,
		        onRender: function(date) {
			    	return date.valueOf() <= checkin.date.valueOf() ? 'disabled' : '';
			    }
		    }).on('changeDate', function(ev) {

		    	var link_id = $(this).attr('rel');
		    	$('#dateTo'+link_id).datepicker('hide');
		        if (!$('#dateFrom'+link_id).val().length) {

		            var newDate = new Date(ev.date)
		            newDate = removeDays(newDate,1);

		            $('#dateFrom'+link_id).datepicker('update',newDate);
		            $('#dateFrom'+link_id).datepicker('hide');

		        }

				writeCookie('searchDateFrom',$('#dateFrom'+link_id).val(),1);
				writeCookie('searchDateTo',  $('#dateTo'+link_id).val(),1);
				writeCookie('searchNumAdults',$('#adults'+link_id).val(),1);
				writeCookie('searchNumChildren',$('#children'+link_id).val(),1);

				$('.dateFrom').val( $('#dateFrom'+link_id).val() );
				$('.dateTo').val( $('#dateTo'+link_id).val() );

				$('select[id^=adults]').val( $('#adults'+link_id).val() );
				$('select[id^=children]').val( $('#children'+link_id).val() );


		    }).on("show", function() {
		        $(this).blur();
		    });

			$(this).blur().focus(); // need to do this, so that when its first initialised, we move out of it, and re-click (otherwise it doesn't open, as we have only just init'd it)
		}

	});

Posting here, just in case anyone comes across it in the future, and wonders what I did :)

**Comment by gmetais** [comment] 2016-01-09 12:51
Nice!

Please tell me if you experience less 255 errors during the next days. It's possibly a problem related to the memory consumption of YLT's DOM access recorder.

**Comment by youradds** [comment] 2016-01-09 13:05
Will do :)

**Comment by gmetais** [comment] 2016-03-20 14:43
Any improvement @youradds?

**Comment by youradds** [comment] 2016-03-21 06:44
It certainly seems much better, yes :) (not had any more of those errors)

**Comment by gmetais** [comment] 2016-03-21 10:51
Thank, I renamed the issue.

**Comment by gmetais** [comment] 2016-06-15 13:19
Closing here, please report similar bugs in #168 .

**Closed by gmetais** 2016-06-15 13:19 UTC
Labels: bug
